# Generated by Django 3.0.5 on 2020-07-11 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20200711_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=250)),
                ('nationality', models.CharField(max_length=64)),
                ('no_of_serving', models.IntegerField()),
                ('picture', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
                ('glutten_free', models.CharField(max_length=1)),
                ('customizable', models.CharField(max_length=1)),
                ('seller', models.ForeignKey(default='DEFAULT VALUE', on_delete=django.db.models.deletion.CASCADE, related_name='cooks', to='user.Seller')),
            ],
        ),
    ]
