# Generated by Django 3.0.5 on 2020-08-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='picture',
            field=models.ImageField(max_length=255, upload_to='dishes/%Y/%m/%d'),
        ),
    ]
