# Generated by Django 3.0.5 on 2020-08-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20200819_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='dishes/%Y/%m/%d'),
        ),
    ]
