# Generated by Django 2.2.13 on 2020-08-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Fast Food'), (2, 'Dessert'), (3, 'Chinese'), (4, 'Thai'), (5, 'Indian'), (6, 'Pakistani'), (7, 'Continental')]),
        ),
    ]
