# Generated by Django 2.2.13 on 2020-08-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_auto_20200819_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='dishes/%Y/%m/%d'),
        ),
    ]
