# Generated by Django 3.0.5 on 2020-08-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_auto_20200820_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='dishes/%Y/%m/%d'),
        ),
    ]
