# Generated by Django 2.2.13 on 2020-08-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_auto_20200820_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Fast Food'), (2, 'Savoury'), (3, 'Dessert'), (4, 'Breakfast'), (5, 'Lunch'), (6, 'Dinner')], default=1),
        ),
        migrations.AlterField(
            model_name='dish',
            name='nationality',
            field=models.PositiveSmallIntegerField(choices=[(1, 'American'), (2, 'French'), (3, 'Chinese'), (4, 'Thai'), (5, 'Indian'), (6, 'Pakistani'), (8, 'Italian'), (9, 'Japanese'), (10, 'Korean'), (11, 'Afghani'), (12, 'Arabian')], default=1),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'American'), (2, 'French'), (3, 'Chinese'), (4, 'Thai'), (5, 'Indian'), (6, 'Pakistani'), (8, 'Italian'), (9, 'Japanese'), (10, 'Korean'), (11, 'Afghani'), (12, 'Arabian')]),
        ),
    ]
