# Generated by Django 2.2.13 on 2020-07-23 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='user',
        ),
        migrations.DeleteModel(
            name='Deliverer',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
