# Generated by Django 3.0.5 on 2020-07-11 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='seller',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='seller',
            name='contact',
            field=models.PositiveIntegerField(default=123),
        ),
        migrations.AddField(
            model_name='seller',
            name='restaurant',
            field=models.CharField(default='Y', max_length=1),
        ),
        migrations.AlterField(
            model_name='seller',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='seller', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
