# Generated by Django 3.0.5 on 2020-07-11 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200711_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='restaurant',
            new_name='homeornot',
        ),
    ]
