# Generated by Django 3.0.5 on 2020-07-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200711_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='homeornot',
            field=models.BooleanField(default=False),
        ),
    ]
