# Generated by Django 3.0.5 on 2020-08-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200713_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='category',
            field=models.CharField(default='Fast food', max_length=100),
        ),
    ]
