# Generated by Django 2.2.13 on 2020-07-23 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20200723_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('phone_number', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
