# Generated by Django 2.2.13 on 2020-08-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='price',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='order_items',
            name='price',
            field=models.FloatField(default=1.0),
        ),
    ]
