# Generated by Django 2.2.13 on 2020-08-19 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliverer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('deliverer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliverer.Deliverer')),
            ],
        ),
    ]
