# Generated by Django 2.2.13 on 2020-08-19 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliverer', '0002_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_Status',
        ),
    ]
