# Generated by Django 2.2.13 on 2020-08-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20200812_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
