# Generated by Django 2.2.13 on 2020-08-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Cash'), (2, 'Paypal'), (3, 'Credit card')], default=1),
        ),
        migrations.DeleteModel(
            name='Order_Status',
        ),
    ]
